### PR TITLE
Update oss.yml

### PR DESCRIPTION
**Pull request by Shadowphax**
Updated the "Run storage service setup script" section which deals with the registration of the storage endpoints with the BeeGFS management service. The nodes were not registering due to duplication from other endpoints.

### CODE REVIEW

**Comment by Shadowphax** [comment]
For some reason it does not seem to work. Unless I am misunderstanding its use. The registration of nodes without {{ ansible_facts['hostname'] }} produces the registration of only the multi-mode services on one host and not the others. How am I meant to use 
`beegfs_mgmt_host: "{{ groups['cluster_beegfs_mgmt'] | first }}"`

Storage
==========
```
bgfs-1-8003 [ID: 1]: reachable at 192.168.100.9:8003 (protocol: TCP)
bgfs-1-8103 [ID: 2]: reachable at 192.168.100.9:8103 (protocol: TCP)
```

**Comment by Shadowphax** [comment]
Only one management host. You can have more than one management host if you plan to host more than one client mount. But then it becomes rather complex if you using a " process per disk " approach.

**Comment by brtknr** [comment]
Often if something isn't working for some reason, I add `-e beegfs_force_format=yes` flag to ansible-playbook. Is that an option for you?

**Comment by Shadowphax** [comment]
Yes I have used it but it doesn't bring the other storage nodes into registration. I can see why that is as per my initial commit. 

I have deployed 3 storage hosts and explicitly set the `beegfs_mgmt_host: "bgfs-1"` but the outcome is the same even with  `beegfs_mgmt_host: "{{ groups['cluster_beegfs_mgmt'] | first }}"`, which is expected. Deploy is successful but only shows one storage host. 
`Management
==========
bgfs-1.novalocal [ID: 1]: reachable at 192.168.100.9:8008 (protocol: TCP)

Metadata
==========
bgfs-1.novalocal [ID: 1]: reachable at 192.168.100.9:8005 (protocol: TCP)

Storage
==========
bgfs-1-8003 [ID: 1]: reachable at 192.168.100.4:8003 (protocol: TCP)
bgfs-1-8103 [ID: 2]: reachable at 192.168.100.4:8103 (protocol: TCP)
`
When oss.yml is updated with `{{ ansible_facts['hostname'] }}` instead of `{{ beegfs_mgmt_host }}` it registers the storage names correctly with the management host. 

`Management
==========
bgfs-1.novalocal [ID: 1]: reachable at 192.168.100.9:8008 (protocol: TCP)

Metadata
==========
bgfs-1.novalocal [ID: 1]: reachable at 192.168.100.9:8005 (protocol: TCP)

Storage
==========
bgfs-3-8003 [ID: 1]: reachable at 192.168.100.8:8003 (protocol: TCP)
bgfs-2-8003 [ID: 2]: reachable at 192.168.100.4:8003 (protocol: TCP)
bgfs-1-8003 [ID: 3]: reachable at 192.168.100.9:8003 (protocol: TCP)
bgfs-3-8103 [ID: 4]: reachable at 192.168.100.8:8103 (protocol: TCP)
bgfs-2-8103 [ID: 5]: reachable at 192.168.100.4:8103 (protocol: TCP)
bgfs-1-8103 [ID: 6]: reachable at 192.168.100.9:8103 (protocol: TCP)
`

**Comment by brtknr** [comment]
Oh I understand the problem now! Would it still work if ansible_facts['hostname'] is replaced with  inventory_hostname?

**Comment by Shadowphax** [comment]
Apologies for not responding sooner, been in meetings and more meetings. I'm assuming that Ansible is not at fault here. Two things, BeeGFS management node should not be accepting duplicate registrations from storage nodes. Secondly, the BeeGFS storage script to register the nodes includes a -I and -S which would be used a bit better, I think to register the nodes.

**Pull request merged**
